FROM nvidia/cuda:12.2.0-devel-ubuntu20.04 AS builder

ENV DEBIAN_FRONTEND noninteractive
ENV OPENCV_VER 4.8.0
# Install requirements
RUN apt-get update && apt-get install -y \
    # OpenCV dependencies
    build-essential g++ cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev wget unzip \
    python3-dev python3-numpy
    # libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev \
    # libcanberra-gtk-module libcanberra-gtk3-module

# Clone, build and install OpenCV
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/refs/tags/$OPENCV_VER.zip && unzip opencv.zip && mkdir -p build
RUN cd build && cmake ../opencv-$OPENCV_VER && cmake --build .
# RUN make -j"$(nproc)" && make install && rm -rf /opencv
  
FROM builder AS runner 
WORKDIR /ONNX-yolov5
COPY / /ONNX-yolov5

RUN mkdir build && cd build && cmake .. && make -j4

# COPY ..yolov5/yolov5.onnx /

ENTRYPOINT ./build/main yolov5n.onnx 
